<?php

return [
    // Common Texts
    'page_title' => 'Mắt Kính Sài Gòn - Trang chủ',
    'default_title' => 'Sản Phẩm - Mắt Kính Sài Gòn',
    'currency' => 'VNĐ',
    
    // Categories
    'featured_categories' => 'Danh Mục Nổi Bật',
    'category_glasses' => 'GỌNG KÍNH',
    'category_lenses' => 'TRÒNG KÍNH',
    'category_sunglasses' => 'KÍNH MÁT',
    'category_promotion' => 'KHUYẾN MÃI',
    'view_now' => 'Xem Ngay',
    
    // Products
    'newest_products' => 'Sản Phẩm Mới Nhất',
    'newest_news' => 'Tin Tức Mới Nhất',
    'no_products' => 'Không tìm thấy sản phẩm nào',
    'no_products_in_category' => 'Chưa có sản phẩm nào trong danh mục này',
    'add_to_cart' => 'Thêm vào giỏ hàng',
    
    // Filter & Sort
    'frame_style_title' => 'Thương Hiệu',
    'mobile_filter_button' => 'Bộ Lọc Sản Phẩm',
    'filter_title' => 'Bộ Lọc',
    'filter_by_price' => 'TÌM THEO GIÁ',
    'color' => 'Màu Sắc',
    'color_fallback' => 'Màu sắc',
    'material' => 'CHẤT LIỆU',
    
    // Results
    'results_showing' => 'Hiển thị',
    'results_of' => 'của',
    'results' => 'kết quả',
    'results_zero' => 'Hiển thị 0 kết quả',
    
    // Sort Options
    'sort_newest' => 'Mới nhất',
    'sort_price_asc' => 'Giá: Thấp đến Cao',
    'sort_price_desc' => 'Giá: Cao đến Thấp',
    'sort_name_asc' => 'Tên: A-Z',
    'sort_name_desc' => 'Tên: Z-A',
    
    // Price Ranges
    'price_under_500k' => 'Dưới 500k',
    'price_500k_1m' => '500k - 1 Triệu',
    'price_1m_3m' => '1 - 3 Triệu',
    'price_3m_5m' => '3 - 5 Triệu',
    'price_over_5m' => '> 5 Triệu',
    
    // Navigation
    'nav_home' => 'TRANG CHỦ',
    'nav_brand' => 'THƯƠNG HIỆU',
    'nav_about' => 'GIỚI THIỆU',
    'view_all' => 'Xem tất cả',
    
    // Search
    'search_title' => 'Tìm kiếm',
    'search_placeholder' => 'Nhập từ khóa tìm kiếm sản phẩm, tin tức hoặc thương hiệu...',
    'search_button' => 'Tìm',
    'search_all' => 'Tất cả',
    'search_product' => 'Sản phẩm',
    'search_news' => 'Tin tức',
    'search_brand' => 'Thương hiệu',
    'search_partner' => 'Đối tác',
    'search_enter_keyword' => 'Nhập từ khóa để tìm kiếm',
    'search_loading' => 'Đang tìm kiếm...',
    'search_please_enter' => 'Vui lòng nhập từ khóa tìm kiếm',
    'search_error' => 'Có lỗi xảy ra',
    'search_error_message' => 'Có lỗi xảy ra khi tìm kiếm',
    'search_no_results' => 'Không tìm thấy kết quả',
    'search_try_other' => 'Thử với từ khóa khác',
    
    // Footer
    'footer_policy_title' => 'CHÍNH SÁCH & QUY ĐỊNH',
    'footer_legal_title' => 'QUY ĐỊNH PHÁP LÝ',
    'footer_connect_title' => 'KẾT NỐI VỚI CHÚNG TÔI',
    'footer_work_time_title' => 'THỜI GIAN LÀM VIỆC',
    'footer_map_title' => 'BẢN ĐỒ',
    
    // Cart
    'cart_title' => 'Giỏ Hàng',
    'cart_empty' => 'Giỏ hàng trống',
    'cart_total' => 'Tổng cộng:',
    'cart_checkout' => 'Thanh Toán',
    'cart_remove' => 'Xóa',
    
    // Mobile Sidebar
    'mobile_sidebar_sale' => 'ĐANG GIẢM GIÁ',
    
    // Mobile Contact Bar
    'mobile_contact_find_way' => 'Tìm đường',
    'mobile_contact_sms' => 'Nhắn SMS',
    'mobile_contact_call' => 'Gọi điện',
    'mobile_contact_messenger' => 'Messenger',
    'mobile_contact_zalo' => 'Chat Zalo',
    
    // Product Detail
    'product_detail_title' => 'Chi Tiết Sản Phẩm - Mắt Kính Sài Gòn',
    'product_free_shipping' => 'Miễn phí vận chuyển',
    'product_shipping_time' => 'Giao nhanh 24-72h toàn quốc',
    'product_return_policy' => 'Đổi trả trong 7 ngày',
    'product_return_free' => 'Miễn phí nếu lỗi từ nhà sản xuất',
    'product_warranty' => 'Bảo hành 12 tháng',
    'product_warranty_info' => 'Chính hãng Helen Keller toàn hệ thống',
    'product_code' => 'Mã SP:',
    'product_brand' => 'Thương Hiệu:',
    'product_share' => 'Chia sẻ',
    'product_save' => 'Tiết kiệm',
    'product_frame_color' => 'Màu gọng',
    'product_selected' => 'Đã chọn',
    'product_lens_package' => 'Chọn gói tròng kính',
    'product_add_to_cart' => 'Thêm vào giỏ hàng',
    'product_buy_now' => 'Mua ngay',
    'product_install_time' => 'Lắp kính trong 30 phút tại cửa hàng',
    'product_hotline' => 'Hotline tư vấn:',
    'product_pickup_showroom' => 'Nhận tại showroom',
    'product_pickup_address' => '301B Điện Biên Phủ, Q.3 - hoặc hệ thống 3 chi nhánh Mắt Kính Sài Gòn.',
    'product_gift' => 'Quà tặng kèm',
    'product_gift_info' => 'Khăn lau & dung dịch vệ sinh kính cao cấp.',
    'product_payment' => 'Thanh toán linh hoạt',
    'product_payment_info' => 'Tiền mặt, chuyển khoản, quẹt thẻ, trả góp.',
    'product_guarantee_title' => 'Cam kết chính hãng 100%',
    'product_guarantee_desc' => 'Sản phẩm Helen Keller nhập khẩu, có đầy đủ tem chống hàng giả, phiếu bảo hành, hóa đơn VAT theo yêu cầu.',
    'product_eye_test_title' => 'Đo thị lực chuẩn quốc tế',
    'product_eye_test_desc' => 'Trang thiết bị Essilor & ZEISS, bác sĩ nhãn khoa nhiều kinh nghiệm. Đặt lịch trước để được ưu tiên.',
    'product_after_sale_title' => 'Hậu mãi trọn đời',
    'product_after_sale_desc' => 'Miễn phí vệ sinh, chỉnh sửa gọng, thay ốc, da mũi, căn chỉnh form trong suốt quá trình sử dụng.',
    'product_tab_description' => 'Mô tả sản phẩm',
    'product_tab_specs' => 'Thông số kỹ thuật',
    'product_tab_services' => 'Dịch vụ & bảo hành',
    'product_tab_faq' => 'Câu hỏi thường gặp',
    'product_tab_address' => 'Địa chỉ bán hàng',
    'product_tab_time' => 'Giờ làm việc',
    'product_no_description' => 'Không có dữ liệu mô tả sản phẩm.',
    'product_no_specs' => 'Không có dữ liệu thông số kỹ thuật.',
    'product_no_services' => 'Không có dữ liệu dịch vụ & bảo hành.',
    'product_no_faq' => 'Không có dữ liệu câu hỏi thường gặp.',
    'product_no_address' => 'Không có dữ liệu địa chỉ bán hàng.',
    'product_no_time' => 'Không có dữ liệu giờ làm việc.',
    'product_showroom_title' => 'Trải nghiệm trực tiếp tại showroom Mắt Kính Sài Gòn',
    'product_showroom_desc' => 'Hệ thống cửa hàng phủ khắp TP.HCM, phục vụ đo mắt chuẩn quốc tế, lắp kính lấy nhanh và chăm sóc sau bán tận tâm.',
    'product_showroom_1' => 'Showroom 1:',
    'product_showroom_1_address' => '301B Điện Biên Phủ, P. Xuân Hòa, TP.HCM',
    'product_showroom_2' => 'Showroom 2:',
    'product_showroom_2_address' => '245C Xô Viết Nghệ Tĩnh, Phường Gia Định, TP.HCM',
    'product_showroom_3' => 'Showroom 3:',
    'product_showroom_3_address' => '90 Nguyễn Hữu Thọ, Phường Bà Rịa, TP.HCM',
    'product_work_time' => 'Giờ làm việc:',
    'product_work_time_value' => 'Thứ 2 - Thứ 7: 08h00 - 20h30 | CN & Lễ: 08h30 - 20h00',
    'product_book_appointment_title' => 'Đặt lịch đo mắt & tư vấn nhanh',
    'product_book_appointment_desc' => 'Điền thông tin dưới đây, chuyên viên sẽ gọi lại trong 10 phút.',
    'product_form_name' => 'Họ và tên',
    'product_form_name_placeholder' => 'Nguyễn Thị Minh Anh',
    'product_form_email' => 'Email',
    'product_form_email_placeholder' => 'email@example.com',
    'product_form_showroom' => 'Showroom gần bạn',
    'product_form_showroom_placeholder' => 'Chọn chi nhánh',
    'product_form_showroom_1' => '301B Điện Biên Phủ, Q.3',
    'product_form_showroom_2' => '245C Xô Viết Nghệ Tĩnh, Bình Thạnh',
    'product_form_showroom_3' => '90 Nguyễn Hữu Thọ, Bà Rịa',
    'product_form_datetime' => 'Thời gian mong muốn',
    'product_form_datetime_hint' => 'Chọn ngày và giờ bạn muốn đặt lịch (giờ làm việc: 08:00 - 20:30)',
    'product_form_message' => 'Nhu cầu hoặc độ kính hiện tại',
    'product_form_message_placeholder' => 'Ví dụ: cần đo lại độ, muốn tư vấn tròng chống ánh sáng xanh...',
    'product_form_submit' => 'Gửi yêu cầu tư vấn',
    'product_form_help' => 'Hoặc liên hệ nhanh:',
    'product_related_title' => 'Sản phẩm liên quan',
    'product_related_add_to_cart' => 'Thêm vào giỏ',
    'product_lightbox_zoom' => 'Phóng to hình sản phẩm',
    'product_lightbox_close' => 'Đóng phóng to hình ảnh',
    'product_lightbox_prev' => 'Hình trước',
    'product_lightbox_next' => 'Hình tiếp theo',
    'product_fallback' => 'Sản phẩm',
    
    // Shopping Cart
    'cart_page_title' => 'Giỏ hàng',
    'cart_order_info_title' => 'Thông tin đơn hàng',
    'cart_order_info_desc' => 'Quản lý các sản phẩm đã chọn, cập nhật số lượng hoặc loại bỏ sản phẩm trước khi thanh toán.',
    'cart_empty_message' => 'Giỏ hàng của bạn đang trống. Hãy tiếp tục mua sắm để thêm sản phẩm vào giỏ.',
    'cart_continue_shopping' => 'Tiếp tục mua sắm',
    'cart_checkout_title' => 'Thông tin giao hàng',
    'cart_checkout_desc' => 'Vui lòng nhập chính xác thông tin để chúng tôi giao hàng nhanh chóng.',
    'cart_form_name' => 'Họ và tên',
    'cart_form_name_placeholder' => 'Nguyễn Văn A',
    'cart_form_gender' => 'Giới tính',
    'cart_form_gender_placeholder' => 'Chọn giới tính',
    'cart_form_gender_male' => 'Nam',
    'cart_form_gender_female' => 'Nữ',
    'cart_form_gender_other' => 'Khác',
    'cart_form_phone' => 'Số điện thoại',
    'cart_form_phone_placeholder' => '0909 999 999',
    'cart_form_email' => 'Email',
    'cart_form_email_placeholder' => 'email@domain.com',
    'cart_form_city' => 'Thành phố',
    'cart_form_city_placeholder' => 'Chọn thành phố',
    'cart_form_district' => 'Xã / Quận',
    'cart_form_district_placeholder' => 'Chọn quận / huyện',
    'cart_form_address' => 'Địa chỉ liên hệ',
    'cart_form_address_placeholder' => 'Số nhà, tên đường, phường/xã...',
    'cart_form_note' => 'Ghi chú cho đơn hàng',
    'cart_form_note_placeholder' => 'Ví dụ: giao giờ hành chính, gọi trước khi giao...',
    'cart_payment_method' => 'Hình thức thanh toán',
    'cart_payment_bank' => 'Chuyển khoản ngân hàng',
    'cart_payment_bank_desc' => 'Thanh toán nhanh qua Vietcombank.',
    'cart_payment_cod' => 'Thanh toán khi nhận hàng (COD)',
    'cart_payment_cod_desc' => 'Giao hàng và thu tiền tận nơi.',
    'cart_payment_store' => 'Đặt hàng và thanh toán tại shop',
    'cart_payment_store_desc' => 'Đến showroom gần nhất để thanh toán.',
    'cart_payment_bank_note' => 'Chuyển khoản ngân hàng:',
    'cart_payment_bank_note_detail' => 'Quý khách chuyển khoản vui lòng để lại SĐT trong phần ghi chú để bộ phận kế toán hỗ trợ nhanh nhất.',
    'cart_payment_bank_name' => 'Ngân hàng Vietcombank',
    'cart_payment_bank_account' => 'Số tài khoản:',
    'cart_payment_bank_account_value' => '8888888.301',
    'cart_payment_bank_owner' => 'Tên chủ TK:',
    'cart_payment_bank_owner_value' => 'Vũ Thị Hảo',
    'cart_payment_cod_note' => 'Thanh toán khi nhận hàng (COD):',
    'cart_payment_cod_note_detail' => 'Miễn phí giao hàng COD cho hóa đơn trên 500.000đ. Phí giao hàng đơn dưới 500k sẽ được thông báo khi nhân viên xác nhận đơn hàng.',
    'cart_payment_store_note' => 'Đặt hàng và thanh toán tại shop:',
    'cart_payment_store_note_detail' => '301B Điện Biên Phủ, Quận 3',
    'cart_payment_store_note_detail_1' => '301B Điện Biên Phủ, Quận 3',
    'cart_payment_store_note_detail_2' => '245C Xô Viết Nghệ Tĩnh, Quận Bình Thạnh',
    'cart_payment_store_note_detail_3' => '90 Nguyễn Hữu Thọ, Bà Rịa',
    'cart_form_cancel' => 'Hủy',
    'cart_form_submit' => 'Xác nhận đặt hàng',
    'cart_processing' => 'Đang xử lý...',
    'cart_empty_alert' => 'Giỏ hàng của bạn đang trống. Vui lòng thêm sản phẩm trước khi thanh toán.',
    'cart_error' => 'Có lỗi xảy ra khi tạo đơn hàng. Vui lòng thử lại.',
    'cart_item_index' => '#',
    'cart_item_unit_price' => 'Đơn giá',
    'cart_item_quantity' => 'Số lượng',
    'cart_item_subtotal' => 'Tạm tính',
    'cart_receipt_title' => 'Hóa đơn tạm tính',
    'cart_receipt_desc' => 'Đây là tóm tắt chi tiết cho giỏ hàng hiện tại',
    'cart_receipt_code' => 'Mã đơn tạm:',
    'cart_receipt_time' => 'Thời gian:',
    'cart_receipt_total_items' => 'Tổng sản phẩm:',
    'cart_receipt_product' => 'Sản phẩm',
    'cart_receipt_quantity' => 'Số lượng',
    'cart_receipt_amount' => 'Thành tiền',
    'cart_receipt_subtotal' => 'Tạm tính',
    'cart_receipt_shipping' => 'Phí vận chuyển',
    'cart_receipt_shipping_free' => 'Miễn phí',
    'cart_receipt_discount' => 'Mã giảm giá',
    'cart_receipt_discount_none' => 'Chưa áp dụng',
    'cart_receipt_total' => 'Tổng thanh toán',
    'cart_receipt_download_pdf' => 'Tải xuống PDF',
    'cart_receipt_continue' => 'Tiếp tục mua sắm',
    'cart_receipt_checkout' => 'Tiến hành thanh toán',
    'cart_receipt_pdf_soon' => 'Tính năng tải PDF sẽ được cập nhật sớm!',
    'cart_brand' => 'Thương hiệu:',
    'cart_option' => 'Tùy chọn:',
    'cart_no_options' => 'Không có tùy chọn bổ sung',
    'cart_unit_price' => 'Đơn giá',
    'cart_subtotal' => 'Tạm tính',
    'cart_decrease' => 'Giảm số lượng',
    'cart_increase' => 'Tăng số lượng',
    'cart_district_no_data' => 'Không có dữ liệu',
    'cart_payment_method_label' => 'Hình thức thanh toán',
    'cart_close' => 'Đóng',
    'cart_option_color' => 'Màu',
    'cart_option_lens' => 'Gói tròng',
    
    // Brand
    'brand_index_title' => 'Thương Hiệu - Mắt Kính Sài Gòn',
    'brand_index_hero_title' => 'Thương Hiệu Nổi Bật',
    'brand_index_hero_desc' => 'Khám phá bộ sưu tập đầy đủ các thương hiệu kính mắt hàng đầu thế giới. Từ những nhà sáng tạo truyền thống đến các thương hiệu thời trang đương đại.',
    'brand_index_no_brands' => 'Hiện tại chưa có thương hiệu nào.',
    'brand_detail_title' => 'Thương Hiệu - Mắt Kính Sài Gòn',
    'brand_detail_showing' => 'Hiển thị',
    'brand_detail_in' => 'trong tổng số',
    'brand_detail_products' => 'sản phẩm',
    'brand_detail_no_products' => 'Không có sản phẩm nào',
    'brand_detail_sort_newest' => 'Mới nhất',
    'brand_detail_sort_price_asc' => 'Giá tăng dần',
    'brand_detail_sort_price_desc' => 'Giá giảm dần',
    'brand_detail_sort_name_asc' => 'Tên A-Z',
    'brand_detail_sort_name_desc' => 'Tên Z-A',
    'brand_detail_category' => 'Danh mục:',
    'brand_detail_all' => 'Tất cả',
    'brand_detail_category_fallback' => 'Danh mục',
    'brand_detail_no_products_brand' => 'Hiện tại chưa có sản phẩm nào cho thương hiệu này.',
    'brand_detail_default_desc' => 'Khám phá bộ sưu tập',
    'brand_detail_default_desc_2' => 'Thương hiệu kính mắt hàng đầu với thiết kế tinh tế và chất lượng vượt trội.',
    
    // Partner
    'partner_index_title' => 'Đối Tác - Mắt Kính Sài Gòn',
    'partner_index_hero_title' => 'Đối Tác Của Chúng Tôi',
    'partner_index_hero_desc' => 'Chúng tôi tự hào hợp tác với những đối tác uy tín và chất lượng hàng đầu. Cùng nhau mang đến những sản phẩm và dịch vụ tốt nhất cho khách hàng.',
    'partner_index_no_partners' => 'Hiện tại chưa có đối tác nào.',
    'partner_detail_title' => 'Đối Tác - Mắt Kính Sài Gòn',
    'partner_detail_contact_title' => 'Thông Tin Liên Hệ',
    'partner_detail_address' => 'Địa chỉ',
    'partner_detail_phone' => 'Điện thoại',
    'partner_detail_email' => 'Email',
    'partner_detail_website' => 'Website',
    'partner_detail_location_title' => 'Vị Trí',
    'partner_detail_view_map' => 'Xem trên Google Maps',
    
    // Policy/Page
    'page_title_default' => 'Trang - Mắt Kính Sài Gòn',
    'page_badge' => 'Chính sách & Quy định',
    'page_back' => 'Quay lại',
    
    // News
    'news_detail_title' => 'Tin Tức - Mắt Kính Sài Gòn',
    'news_detail_category' => 'Tin tức',
    'news_detail_views' => 'lượt xem',
    'news_detail_share' => 'Chia sẻ',
    'news_detail_category_label' => 'Thuộc chuyên mục:',
    'news_detail_related_title' => 'Tin liên quan',
    'news_detail_read_more' => 'Đọc tiếp →',
    'news_detail_read_time' => '5 phút đọc',
    'news_category_title' => 'Tin Tức - Mắt Kính Sài Gòn',
    'news_category_badge' => 'Trang tin Mắt Kính Sài Gòn',
    'news_category_hero_title' => 'Kho kiến thức & bản tin cập nhật cho người yêu đôi mắt',
    'news_category_hero_desc' => 'Cùng khám phá xu hướng kính mới, mẹo chăm sóc mắt và câu chuyện tại hệ thống showroom của Mắt Kính Sài Gòn. Chúng tôi cập nhật mỗi tuần để bạn luôn dẫn đầu phong cách và bảo vệ thị lực tốt nhất.',
    'news_category_location' => '3 showroom tại TP.HCM',
    'news_category_work_time' => 'Thứ 2 - Thứ 7: 08h00 - 20h30',
    'news_category_hotline' => 'Hotline: 0888 368 888',
    'news_category_search_placeholder' => 'Tìm kiếm bài viết, chủ đề hoặc thương hiệu...',
    'news_category_all' => 'Tất cả',
    'news_category_no_posts' => 'Hiện chưa có bài viết nào.',
    'news_category_pagination_prev' => 'Trang trước',
    'news_category_pagination_next' => 'Trang tiếp theo',
    'news_category_fallback' => 'Danh mục',
    'news_category_filter_knowledge' => 'Kiến thức mắt',
    'news_category_filter_trend' => 'Xu hướng kính',
    'news_category_filter_care' => 'Chăm sóc mắt',
    'news_category_filter_event' => 'Sự kiện nổi bật',
    'news_category_pagination_label' => 'Phân trang bài viết',
    
    // Shopping Cart Page - Additional
    'cart_page_title_default' => 'Giỏ Hàng - Mắt Kính Sài Gòn',
    'cart_continue_shopping_btn' => 'Tiếp tục mua sắm',
    'cart_option_label' => 'Tùy chọn:',
    'cart_option_none' => 'Không có',
    'cart_receipt_product_list_label' => 'Danh sách sản phẩm trong giỏ',
    'cart_receipt_totals_label' => 'Chi tiết thanh toán',
    
    // Common Alt Text
    'alt_logo' => 'Mắt Kính Sài Gòn',
    'alt_logo_premium' => 'Mắt Kính Hàng Hiệu',
];
